import { CheckCircle2, Image, LoaderCircle, ShieldCheck, Sparkles, X } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { api } from '../api'
import { preferredProvider } from '../preferences'
import type { LlmStatus, MangaPage, MeaningCheckResult } from '../types'
import { AiProviderStatus } from './AiProviderStatus'
import { MeaningResults } from './MeaningResults'

export function MeaningCheck({volumeId,pageIndex,page,onClose,hidden=false}:{volumeId:string;pageIndex:number;page:MangaPage;onClose:()=>void;hidden?:boolean}){
  const [answers,setAnswers]=useState<Record<number,string>>({});const[includeArtwork,setIncludeArtwork]=useState(false);const[question,setQuestion]=useState('');const[status,setStatus]=useState<LlmStatus|null>(null);const[provider,setProvider]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<MeaningCheckResult|null>(null)
  useEffect(()=>{api.llmStatus().then((value)=>{setStatus(value);setProvider(preferredProvider(value))}).catch((reason)=>setError(reason.message))},[])
  const submitted=useMemo(()=>Object.entries(answers).filter(([,value])=>value.trim()).map(([block_index,interpretation])=>({block_index:Number(block_index),interpretation:interpretation.trim()})),[answers])
  async function check(){setBusy(true);setError('');try{const checked=await api.meaningCheck(volumeId,pageIndex,submitted,includeArtwork,question,provider);setResult(checked);checked.check.evaluations.forEach((item)=>api.assistance(volumeId,pageIndex,item.meaning_score>=80?'comprehension_success':'comprehension_gap',item.block_index).catch(()=>undefined))}catch(reason){setError(reason instanceof Error?reason.message:'Meaning Check failed')}finally{setBusy(false)}}
  function grow(event:FormEvent<HTMLTextAreaElement>){const field=event.currentTarget;field.style.height='auto';field.style.height=`${field.scrollHeight}px`}
  return <aside className="tool-panel meaning-check" hidden={hidden}><header><div><span className="eyebrow">TEST BEFORE REVEAL</span><h2>Meaning Check</h2></div><button className="icon-button" aria-label="Close panel" onClick={onClose}><X size={19}/></button></header>
    {!result&&<><div className="meaning-intro"><CheckCircle2 size={25}/><div><strong>What did you understand?</strong><p>Write your reading of any bubbles below. Unanswered text stays unrevealed. Everything is evaluated in one page-level request.</p></div></div><div className="meaning-blocks">{page.blocks.map((block,index)=>{const japanese=block.lines.join('');if(!japanese)return null;return <label key={index}><span><b>{String(index+1).padStart(2,'0')}</b><i>{japanese}</i></span><textarea value={answers[index]||''} onInput={grow} onChange={(event)=>setAnswers({...answers,[index]:event.target.value})} placeholder="What do you think this means?"/></label>})}</div><label className="meaning-artwork-toggle"><input type="checkbox" checked={includeArtwork} onChange={(event)=>setIncludeArtwork(event.target.checked)}/><Image size={17}/><div><strong>Include page artwork</strong><span>Off by default. Enable when expressions, speakers, or reactions depend on the image.</span></div></label><label className="meaning-question"><span>PARTICULAR CONCERN <i>optional</i></span><textarea value={question} onInput={grow} onChange={(event)=>setQuestion(event.target.value)} placeholder="For example: I am unsure who the implied subject is."/></label><div className="meaning-privacy"><ShieldCheck size={15}/> Nothing is shared until you run the check.</div><AiProviderStatus status={status} provider={provider}/><button className="primary-button meaning-submit" disabled={!submitted.length||!provider||busy} onClick={check}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'Comparing the page…':`Check ${submitted.length||''} ${submitted.length===1?'bubble':'bubbles'}`}</button></>}
    {error&&<div className="error-note">{error}</div>}{result&&<><MeaningResults summary={result.check.summary} evaluations={result.check.evaluations} answers={answers}/><div className="meaning-saved"><ShieldCheck size={14}/><span>Saved locally in Page Lens → Past AI queries.</span></div><button className="secondary-button meaning-again" onClick={()=>setResult(null)}>Revise my answers and check again</button></>}
  </aside>
}
