import { ArrowDown, ArrowUp, CheckCircle2, HelpCircle, Image, LoaderCircle, ShieldCheck, Sparkles, X } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { api } from '../api'
import { preferredProvider } from '../preferences'
import type { LlmStatus, MangaPage, MeaningCheckResult } from '../types'
import { AiProviderStatus } from './AiProviderStatus'
import { MeaningResults } from './MeaningResults'

export function MeaningCheck({volumeId,pageIndex,page,onClose,hidden=false}:{volumeId:string;pageIndex:number;page:MangaPage;onClose:()=>void;hidden?:boolean}){
  const [answers,setAnswers]=useState<Record<number,string>>({});const[unable,setUnable]=useState<Set<number>>(new Set());const[order,setOrder]=useState(()=>page.blocks.map((_,index)=>index));const[includeArtwork,setIncludeArtwork]=useState(false);const[question,setQuestion]=useState('');const[status,setStatus]=useState<LlmStatus|null>(null);const[provider,setProvider]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<MeaningCheckResult|null>(null)
  useEffect(()=>{api.llmStatus().then((value)=>{setStatus(value);setProvider(preferredProvider(value))}).catch((reason)=>setError(reason.message))},[])
  const submitted=useMemo(()=>order.filter((index)=>unable.has(index)||(answers[index]||'').trim()).map((block_index)=>({block_index,interpretation:(answers[block_index]||'').trim(),unable:unable.has(block_index)})),[answers,order,unable])
  async function check(){setBusy(true);setError('');try{const checked=await api.meaningCheck(volumeId,pageIndex,submitted,includeArtwork,question,provider);setResult(checked);checked.check.evaluations.forEach((item)=>api.assistance(volumeId,pageIndex,item.meaning_score>=80?'comprehension_success':'comprehension_gap',item.block_index).catch(()=>undefined))}catch(reason){setError(reason instanceof Error?reason.message:'Meaning Check failed')}finally{setBusy(false)}}
  function grow(event:FormEvent<HTMLTextAreaElement>){const field=event.currentTarget;field.style.height='auto';field.style.height=`${field.scrollHeight}px`}
  function moveBlock(position:number,delta:number){const target=position+delta;if(target<0||target>=order.length)return;setOrder((current)=>{const next=[...current];[next[position],next[target]]=[next[target],next[position]];return next})}
  function toggleUnable(index:number){setUnable((current)=>{const next=new Set(current);if(next.has(index))next.delete(index);else next.add(index);return next})}
  return <aside className="tool-panel meaning-check" hidden={hidden}><header><div><span className="eyebrow">TEST BEFORE REVEAL</span><h2>Meaning Check</h2></div><button className="icon-button" aria-label="Close panel" onClick={onClose}><X size={19}/></button></header>
    {!result&&<><div className="meaning-intro"><CheckCircle2 size={25}/><div><strong>What did you understand?</strong><p>Put bubbles in reading order, then translate what you can. Mark unknown bubbles instead of guessing; all selected bubbles are handled in one page-level request.</p></div></div><div className="meaning-blocks">{order.map((index,position)=>{const block=page.blocks[index];const japanese=block?.lines.join('');if(!japanese)return null;const isUnable=unable.has(index);return <section key={index} className={isUnable?'is-unable':''}><div className="meaning-block-heading"><span><b>{String(position+1).padStart(2,'0')}</b><i>{japanese}</i></span><div className="meaning-order-actions"><button aria-label={`Move bubble ${position+1} up`} title="Move up" disabled={position===0} onClick={()=>moveBlock(position,-1)}><ArrowUp size={14}/></button><button aria-label={`Move bubble ${position+1} down`} title="Move down" disabled={position===order.length-1} onClick={()=>moveBlock(position,1)}><ArrowDown size={14}/></button></div></div><textarea aria-label={`Your translation for bubble ${position+1}`} value={answers[index]||''} disabled={isUnable} onInput={grow} onChange={(event)=>setAnswers({...answers,[index]:event.target.value})} placeholder="What do you think this means?"/><button className="meaning-unable" aria-pressed={isUnable} onClick={()=>toggleUnable(index)}><HelpCircle size={14}/>{isUnable?'Marked as unknown — include it':'I can’t translate this'}</button></section>})}</div><label className="meaning-artwork-toggle"><input type="checkbox" checked={includeArtwork} onChange={(event)=>setIncludeArtwork(event.target.checked)}/><Image size={17}/><div><strong>Include page artwork</strong><span>Off by default. Enable when expressions, speakers, or reactions depend on the image.</span></div></label><label className="meaning-question"><span>PARTICULAR CONCERN <i>optional</i></span><textarea value={question} onInput={grow} onChange={(event)=>setQuestion(event.target.value)} placeholder="For example: I am unsure who the implied subject is."/></label><div className="meaning-privacy"><ShieldCheck size={15}/> Nothing is shared until you run the check.</div><AiProviderStatus status={status} provider={provider}/><button className="primary-button meaning-submit" disabled={!submitted.length||!provider||busy} onClick={check}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'Comparing the page…':`Check ${submitted.length||''} ${submitted.length===1?'bubble':'bubbles'}`}</button></>}
    {error&&<div className="error-note">{error}</div>}{result&&<><MeaningResults summary={result.check.summary} evaluations={result.check.evaluations} answers={{...answers,...Object.fromEntries([...unable].map((index)=>[index,"I couldn’t translate this block."]))}}/><div className="meaning-saved"><ShieldCheck size={14}/><span>Saved locally in Page Lens → Past AI queries.</span></div><button className="secondary-button meaning-again" onClick={()=>setResult(null)}>Revise my answers and check again</button></>}
  </aside>
}
